// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpkybrcjcoxhkifnbxei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwa3licmNqY294aGtpZm5ieGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTY3NjMsImV4cCI6MjA3MzY5Mjc2M30.e0Pr-LsXuwszeObwemAzdjfxZzh8wCxS2tuMFeSs8TE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});